# basic options
title: Vakantie September 2017
author: Teksten geschreven door Kees
description: Website gemaakt door Kees
URL: "https://prudento-nl.github.io/2017-09-frankrijk"

# Build settings
markdown: kramdown
theme: minima
