# basic options
title: Vakantie Juni 2018 - Frankrijk
author: Kees
description: Blog van de kampeervakantie van juni 2018
baseurl: "/2018-06-kamperen-frankrijk"
url: "https://prudento-nl.github.io" 
images: "https://prudento-nl.github.io/2018-06-kamperen-frankrijk/images"

# Build settings
markdown: kramdown
theme: minima

minima:
  date_format: "%d-%m-%Y"
